[project]
name = "travel-agent-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sean Robertson", email = "swrobertson0@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
travel-agent-assistant = "travel_agent_assistant:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
